services:
  gateway:
    image: andrewli2048/celebi-api
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: ${BUILD_TARGET:-dev}
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
        - action: rebuild
          path: ./pyproject.toml
    ports:
      - "9000:9000"
    stop_signal: SIGINT
    restart: always
